name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Navigate to the project directory (if in a subfolder)
      - name: Set up project directory
        working-directory: my-angular-project # Change to your project folder

      # Step 3: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the Angular app
      - name: Build Angular app
        run: npm run build -- --output-path=dist/my-portfolio --base-href=/my-portfolio/

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/my-portfolio
